FROM  ollama/ollama

ARG MODELS="mxbai-embed-large llama3.2:3b"

RUN ollama serve & server=$! ; sleep 5 ; for m in $MODELS ; do ollama pull $m ; done ; kill $server

ENTRYPOINT ["/bin/ollama"]

CMD ["serve"]